interface InitialValuesExportarAgremiacao {
  Nome: boolean,
  Sigla: boolean,
  Fantasia: boolean,
  Responsavel: boolean,
  Representante: boolean,
  DataFiliacao: boolean,
  DataNascimento: boolean,
  Cep: boolean,
  Endereco: boolean,
  Bairro: boolean,
  Complemento: boolean,
  CidadeNome: boolean,
  EstadoNome: boolean,
  PaisNome: boolean,
  Telefone: boolean,
  Email: boolean,
  Cnpj: boolean,
  RegiaoNome: boolean
}

export const values: InitialValuesExportarAgremiacao = {
  Nome: false,
  Sigla: false,
  Fantasia: false,
  Responsavel: false,
  Representante: false,
  DataFiliacao: false,
  DataNascimento: false,
  Cep: false,
  Endereco: false,
  Bairro: false,
  Complemento: false,
  CidadeNome: false,
  EstadoNome: false,
  PaisNome: false,
  Telefone: false,
  Email: false,
  Cnpj: false,
  RegiaoNome: false
}